#!/usr/bin/env bash

# Reference: https://github.com/natemaia/dk

# =====================================================================
# autostart programs
# =====================================================================

# Start Polybar
$HOME/.config/dk/polybar/launch.sh &

# Start sxhkd for keybindings
sxhkd -c $HOME/.config/dk/sxhkdrc &

# Set xrandr scaling variables (percentage)
#x125="1.6x1.6"
#x133="1.5x1.5"
#x150="1.33333333x1.33333333"
#x160="1.25x1.25"
#x175="1.14285714x1.14285714"

# Set display scaling (using xrandr)
#xrandr --output HDMI-A-0 --scale $x175 &

# Start XDG autostart .desktop files (using dex)
dex --autostart --environment dk &

# Start xss-lock and set dpms time to trigger xss-lock
xss-lock -l -- i3lock -n -c 202a36 &
sleep 1; xset dpms 300 300 300 &

# Start polkit authentication agent
/usr/libexec/polkit-mate-authentication-agent-1 &
#/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# Start dunst for notifications
dunst &

# Set wallpaper with nitrogen
sleep 0.75; nitrogen --restore &

# Start xbindkeys to mod keybindings
#xbindkeys &

# Start at-spi d-bus
#/usr/lib/at-spi-bus-launcher --launch-immediately &

# =====================================================================
# dk settings
# =====================================================================

# workspaces
dkcmd set numws=9
dkcmd set ws=_ apply layout=tile master=1 stack=3 gap=16 msplit=0.5 ssplit=0.5

# window behavior/settings
dkcmd set focus_open=true focus_urgent=true focus_mouse=true
dkcmd set tile_tohead=0 tile_hints=false
dkcmd set win_minwh=50 win_minxy=10
dkcmd set smart_gap=false smart_border=false
dkcmd set mouse mod=super move=button1 resize=button3

# window borders
dkcmd set border width=4 outer_width=0 \
    colour \
    focus='#15539e' \
    unfocus='#535353' \
    urgent='#a80e15' \
    outer_focus='#0f0f0f' \
    outer_unfocus='#0f0f0f' \
    outer_urgent='#0f0f0f'

# window rules
dkcmd rule class="^(alacritty|kitty|xterm|xterm-256color)$" terminal=true
dkcmd rule class="^(Atril|Soundconverter)$" float=true w=1600 h=1600 x=center y=center
dkcmd rule class="^(Dconf-editor|qt.*ct|Ristretto)$" float=true w=1440 h=1152 x=center y=center
dkcmd rule class="^(Engrampa|Lxappearance|Xarchiver)$" float=true w=1280 h=1080 x=center y=center
dkcmd rule class="^(flameshot|Galculator|Gnome-disks)$" float=true x=center y=center
dkcmd rule class="^(GParted|Timeshift-gtk|Xfburn)$" float=true w=1920 h=1280 x=center y=center
dkcmd rule class="^(Gpick|Pavucontrol|pavucontrol-qt)$" float=true w=1440 h=1080 x=center y=center
dkcmd rule class="^(imv|mpv|Parole|vlc)$" float=true w=1440 h=900 x=center y=center
dkcmd rule class="^(Lightdm.*settings|Nitrogen)$" float=true w=1080 h=1080 x=center y=center
dkcmd rule apply '*'
