[Places]
HiddenPlaces=menu://applications/

[Sizes]
SplitterPos=142
WindowSize=@Size(700 562)

[View]
BigIconSize=48
HiddenColumns=4, 6, 7
Mode=Detailed
ScrollPerPixel=true
ShowHidden=true
ShowThumbnails=true
SidePaneIconSize=16
SmallIconSize=24
SortColumn=name
SortFolderFirst=true
SortOrder=ascending
ThumbnailIconSize=96
