[General]
__userfile__=true
backlightIdleness=0
backlightIdlenessOnBatteryDischarging=true
disableIdlenessWhenFullscreen=false
enableBatteryWatcher=false
enableExtMonLidClosedActions=false
enableIdlenessBacklightWatcher=false
enableIdlenessWatcher=true
enableLidWatcher=true
hibernateKeyAction=-1
idlenessACAction=5
idlenessACTime=@Variant(\0\0\0\xf\0\t'\xc0)
idlenessBatteryAction=4
idlenessBatteryTime=@Variant(\0\0\0\xf\0\t'\xc0)
idlenessTime=@Variant(\0\0\0\xf\0\0\x3\xe8)
lidClosedAcAction=4
lidClosedAction=4
lidClosedExtMonAcAction=-1
lidClosedExtMonAction=-1
powerKeyAction=3
runCheckLevel=1
suspendKeyAction=4
