#!/usr/bin/env bash

# Reference: https://berrywm.org/configuration.html

# =====================================================================
# autostart programs
# =====================================================================

# Start Polybar
~/.config/polybar/launch.sh &

# Start sxhkdrc
sxhkd -c $HOME/.config/berry/sxhkdrc &

# xrandr scaling reference
# 125% = 1.6x1.6
# 133% = 1.5x1.5
# 150% = 1.33333333x1.33333333
# 160% = 1.25x1.25
# 175% = 1.14285714x1.14285714

# Set display scaling (using xrandr)
#xrandr --output HDMI-A-0 --scale 1.14285714x1.14285714 &

# Start XDG autostart .desktop files (using dex)
dex --autostart --environment berry &

# Start xss-lock and set dpms time to trigger xss-lock
xss-lock -l -- i3lock -n -c 202a36 &
sleep 1; xset dpms 300 300 300 &

# Start polkit authentication agent
/usr/libexec/polkit-mate-authentication-agent-1 &
#/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# Start dunst for notifications
dunst &

# Set wallpaper with nitrogen
sleep 0.75; nitrogen --restore &

# =====================================================================
# berry settings
# =====================================================================

# Set decoration geometry
berryc border_width       4
berryc inner_border_width 0
berryc title_height       0
berryc top_gap            41

# Set decoration colors
berryc focus_color         1c6dcf
berryc unfocus_color       535353
berryc inner_focus_color   0f0f0f
berryc inner_unfocus_color 0f0f0f
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc set_font              "SovranMono-10"
berryc draw_text             "false"
berryc smart_place           "true"
berryc edge_lock             "true"
berryc focus_follows_pointer "true"
berryc resize_mask           "mod4"
berryc resize_button         3
