# Please see https://github.com/bulletmark/libinput-gestures
# for installation instructions and configuration options

##############################################################
# Switch to next / prev workspace with touchpad swipe gestures
##############################################################

gesture swipe left	_internal -w ws_left

gesture swipe right	_internal -w ws_right
