[General]
bgColor=@Variant(\0\0\0\x43\x1\xff\xff\x1e\x1e\x1e\x1e\x1e\x1e\0\0)
fallbackIconTheme=oxygen
fullScreenBgColor=@Variant(\0\0\0\x43\x1\xff\xff\xf\xf\xf\xf\xf\xf\0\0)
maxRecentFiles=6
recentlyOpenedFiles=/home/e33/Pictures/screenshot_2024-06-25_23-27-39.png
slideShowInterval=3
sorting=name

[Thumbnail]
MaxThumbnailFileSize=16384
ShowThumbnails=false
ThumbnailSize=64
ThumbnailsPosition=bottom

[Window]
ExifDatakWidth=250
FixedHeight=500
FixedWidth=700
ForceZoomFit=false
LastWindowHeight=500
LastWindowMaximized=false
LastWindowWidth=700
PrefSize=@Size(456 400)
RememberWindowSize=false
ShowAnnotationsToolbar=false
ShowExifData=false
ShowMenubar=true
ShowOutline=false
ShowToolbar=true
SmoothOnZoom=true
UseTrash=true
