[General]
BuiltinFunction=#fc618d
comment=#807e84
cssValue=#948ae3
function=#79c4ea
keyWord=#7bd88f
number=#9389e2
other=#53e1e2
quote=#fce566
regex=#fd9353
type=#ff79c6
xmlElement=#fb628c

[curLineHighlight]
value=-1

[whiteSpace]
value=68
